package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"text/template"

	ir "github.com/openshift-online/rh-trex-ai/scripts/openapi-ir"
)

var (
	modulePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._~/-]*$`)
	binaryPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	aliasPattern  = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)
)

const (
	outputMarker        = ".trex-tui-generated"
	outputMarkerContent = "Generated by trex-tui-generator. Safe to replace.\n"
)

type generateOptions struct {
	SpecPath string
	OutDir   string
	Module   string
	Binary   string
}

type templateData struct {
	Module string
	Binary string
}

func generate(options generateOptions) error {
	if options.SpecPath == "" || options.OutDir == "" {
		return fmt.Errorf("--spec and --out are required")
	}
	if !modulePattern.MatchString(options.Module) {
		return fmt.Errorf("unsafe generated module path %q", options.Module)
	}
	if !binaryPattern.MatchString(options.Binary) {
		return fmt.Errorf("unsafe generated binary name %q", options.Binary)
	}
	document, err := ir.Load(options.SpecPath, ir.LoadOptions{})
	if err != nil {
		return fmt.Errorf("load canonical OpenAPI IR: %w", err)
	}
	descriptor, err := projectDocument(document)
	if err != nil {
		return fmt.Errorf("validate TUI projection: %w", err)
	}
	parent, err := filepath.Abs(filepath.Dir(options.OutDir))
	if err != nil {
		return fmt.Errorf("resolve output parent: %w", err)
	}
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return fmt.Errorf("create output parent: %w", err)
	}
	stage, err := os.MkdirTemp(parent, ".tui-stage-")
	if err != nil {
		return fmt.Errorf("create TUI staging directory: %w", err)
	}
	keepStage := false
	defer func() {
		if !keepStage {
			_ = os.RemoveAll(stage)
		}
	}()
	data := templateData{Module: options.Module, Binary: options.Binary}
	if err := renderTemplate("templates/go.mod.tmpl", filepath.Join(stage, "go.mod"), data); err != nil {
		return err
	}
	if err := renderTemplate("templates/go.sum.tmpl", filepath.Join(stage, "go.sum"), data); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(stage, outputMarker), []byte(outputMarkerContent)); err != nil {
		return err
	}
	mainPath, err := ir.SafeJoin(stage, "cmd", options.Binary, "main.go")
	if err != nil {
		return err
	}
	if err := renderTemplate("templates/main.go.tmpl", mainPath, data); err != nil {
		return err
	}
	assets, err := fs.Glob(generatorAssets, "internal/tui/*.go")
	if err != nil {
		return fmt.Errorf("enumerate runtime assets: %w", err)
	}
	sort.Strings(assets)
	for _, asset := range assets {
		content, readErr := generatorAssets.ReadFile(asset)
		if readErr != nil {
			return fmt.Errorf("read runtime asset %s: %w", asset, readErr)
		}
		if !bytes.HasPrefix(content, []byte("// Code generated")) {
			content = append([]byte("// Code generated by trex-tui-generator; DO NOT EDIT.\n"), content...)
		}
		target, joinErr := ir.SafeJoin(stage, filepath.FromSlash(asset))
		if joinErr != nil {
			return joinErr
		}
		if writeErr := writeFile(target, content); writeErr != nil {
			return writeErr
		}
	}
	descriptorData, err := json.MarshalIndent(descriptor, "", "  ")
	if err != nil {
		return fmt.Errorf("encode TUI descriptor: %w", err)
	}
	descriptorData = append(descriptorData, '\n')
	descriptorPath, err := ir.SafeJoin(stage, "internal", "tui", "descriptor.json")
	if err != nil {
		return err
	}
	if err := writeFile(descriptorPath, descriptorData); err != nil {
		return err
	}
	if err := replaceOutput(stage, options.OutDir); err != nil {
		return err
	}
	keepStage = true
	return nil
}

func renderTemplate(asset, target string, data templateData) error {
	content, err := generatorAssets.ReadFile(asset)
	if err != nil {
		return fmt.Errorf("read template %s: %w", asset, err)
	}
	tmpl, err := template.New(filepath.Base(asset)).Option("missingkey=error").Parse(string(content))
	if err != nil {
		return fmt.Errorf("parse template %s: %w", asset, err)
	}
	var rendered bytes.Buffer
	if err := tmpl.Execute(&rendered, data); err != nil {
		return fmt.Errorf("render template %s: %w", asset, err)
	}
	return writeFile(target, rendered.Bytes())
}

func writeFile(target string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create generated directory: %w", err)
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		return fmt.Errorf("write generated file %s: %w", target, err)
	}
	return nil
}

func replaceOutput(stage, output string) error {
	output, err := filepath.Abs(output)
	if err != nil {
		return fmt.Errorf("resolve output: %w", err)
	}
	if filepath.Base(output) == "." || filepath.Dir(output) == output {
		return fmt.Errorf("refusing unsafe output path %q", output)
	}
	hadOutput, err := replaceableOutput(output)
	if err != nil {
		return err
	}
	var backup string
	if hadOutput {
		backup, err = os.MkdirTemp(filepath.Dir(output), ".tui-backup-")
		if err != nil {
			return fmt.Errorf("reserve previous TUI output: %w", err)
		}
		if err := os.Remove(backup); err != nil {
			return fmt.Errorf("prepare previous TUI output: %w", err)
		}
		if err := os.Rename(output, backup); err != nil {
			return fmt.Errorf("stage previous TUI output: %w", err)
		}
	}
	if err := os.Rename(stage, output); err != nil {
		if hadOutput {
			_ = os.Rename(backup, output)
		}
		return fmt.Errorf("install generated TUI: %w", err)
	}
	if hadOutput {
		if err := os.RemoveAll(backup); err != nil {
			return fmt.Errorf("remove previous generated TUI: %w", err)
		}
	}
	return nil
}

func replaceableOutput(output string) (bool, error) {
	info, err := os.Lstat(output)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("inspect existing TUI output: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return false, fmt.Errorf("refusing to replace non-directory or symbolic-link output %q", output)
	}
	entries, err := os.ReadDir(output)
	if err != nil {
		return false, fmt.Errorf("inspect existing TUI output: %w", err)
	}
	if len(entries) == 0 {
		return true, nil
	}
	markerPath := filepath.Join(output, outputMarker)
	markerInfo, err := os.Lstat(markerPath)
	if err != nil || !markerInfo.Mode().IsRegular() {
		return false, fmt.Errorf("refusing to replace unowned output %q: missing regular %s marker", output, outputMarker)
	}
	content, err := os.ReadFile(markerPath)
	if err != nil {
		return false, fmt.Errorf("read existing TUI output marker: %w", err)
	}
	if string(content) != outputMarkerContent {
		return false, fmt.Errorf("refusing to replace unowned output %q: invalid %s marker", output, outputMarker)
	}
	return true, nil
}
